# Generated by Django 3.0.11 on 2021-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('slack', 'Slack'), ('google', 'Google')], max_length=255, verbose_name='Name'),
        ),
    ]
