# Generated by Django 3.0.11 on 2021-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210516_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dnd',
            field=models.BooleanField(null=True, verbose_name='Account Do Not Disturb'),
        ),
    ]
