# Generated by Django 3.0.11 on 2021-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_dnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Emoji'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Status'),
        ),
    ]
