# Generated by Django 3.0.11 on 2021-05-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('accounts', '0004_auto_20210518_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='social_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naptime_accounts', to='socialaccount.SocialAccount'),
        ),
    ]
