# Generated by Django 3.0.11 on 2021-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Status message'),
        ),
    ]
