# Generated by Django 3.0.11 on 2021-05-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('naps', '0002_auto_20210511_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.EventInstance', verbose_name='Event Instance'),
        ),
    ]
