# Generated by Django 3.0.11 on 2021-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('naps', '0004_auto_20210511_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='accounts',
            field=models.ManyToManyField(limit_choices_to={'provider__type': 'COMM'}, related_name='naps', to='accounts.Account', verbose_name='Account to nap'),
        ),
    ]
