# Generated by Django 3.0.11 on 2021-05-11 19:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('naps', '0005_auto_20210511_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
