# Generated by Django 3.0.11 on 2021-05-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('naps', '0006_auto_20210511_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='nap',
            name='end_task',
            field=models.OneToOneField(blank=True, help_text="This is the task that end's a nap", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.PeriodicTask', verbose_name='End Task'),
        ),
        migrations.AddField(
            model_name='nap',
            name='start_task',
            field=models.OneToOneField(blank=True, help_text="This is the task that starts's a nap", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.PeriodicTask', verbose_name='Start Task'),
        ),
    ]
